# Generated by Django 5.2.5 on 2025-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(choices=[('indigency', 'Certificate of Indigency'), ('residency', 'Certificate of Residency'), ('clearance', 'Barangay Clearance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
