# Generated by Django 5.1.6 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='generated_docx',
            field=models.FileField(blank=True, null=True, upload_to='generated/docx/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated/pdf/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PRINTED', 'Printed')], default='DRAFT', max_length=20),
        ),
    ]
