# Generated by Django 5.2.5 on 2025-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_type', models.CharField(blank=True, max_length=32, null=True)),
                ('id_number', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
