# Generated by Django 5.2.5 on 2025-08-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_idextract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDExtract',
        ),
    ]
