# Generated by Django 5.2.5 on 2025-09-09 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
