# Generated by Django 5.2.5 on 2025-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificate_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
