# Generated by Django 5.1.7 on 2025-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_adminsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
