# Generated by Django 5.1.7 on 2025-09-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_alter_certificate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('clearance', 'Clearance'), ('residency', 'Residency'), ('indigency', 'Indigency')], max_length=50, unique=True)),
                ('file', models.FileField(upload_to='certificate_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
