# Generated by Django 5.1.7 on 2025-09-20 17:50

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_certificatetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='file',
            field=models.FileField(upload_to=certificates.models.CertificateTemplate.template_upload_path),
        ),
    ]
