# Generated by Django 5.1.6 on 2025-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_alter_certificatetemplate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='resident_since',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
