# Generated by Django 5.1.7 on 2025-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reissue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
