# Generated by Django 5.1.7 on 2025-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_certificate_reissue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsignature',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='adminsignature',
            name='bypass_digital_signature',
            field=models.BooleanField(default=False, help_text='If true, certificates will leave space for manual signing.'),
        ),
        migrations.AlterField(
            model_name='adminsignature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
