# Generated by Django 5.1.7 on 2025-10-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0020_accessattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reissued',
            field=models.BooleanField(default=False),
        ),
    ]
