# Generated by Django 5.1.7 on 2025-10-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0021_certificate_reissued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReissueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reissued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reissue_logs', to='certificates.certificate')),
            ],
        ),
    ]
